application: e6998photo 
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
  expiration : "1d"

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /static
  static_dir: static
  expiration : "1d"
  secure: optional
  
- url: /admin/.*
  script: admin.py
  login: admin
  secure: optional
  
- url: .*
  script: main.py
  secure: optional
